// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.13.0
// source: ptrav/ptrav.proto

package ptrav

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type PathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ptrav_ptrav_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ptrav_ptrav_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_ptrav_ptrav_proto_rawDescGZIP(), []int{0}
}

func (x *PathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// The response message containing the greetings
type ContentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ContentReply) Reset() {
	*x = ContentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ptrav_ptrav_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentReply) ProtoMessage() {}

func (x *ContentReply) ProtoReflect() protoreflect.Message {
	mi := &file_ptrav_ptrav_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentReply.ProtoReflect.Descriptor instead.
func (*ContentReply) Descriptor() ([]byte, []int) {
	return file_ptrav_ptrav_proto_rawDescGZIP(), []int{1}
}

func (x *ContentReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ptrav_ptrav_proto protoreflect.FileDescriptor

var file_ptrav_ptrav_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x74, 0x72, 0x61, 0x76, 0x2f, 0x70, 0x74, 0x72, 0x61, 0x76, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x74, 0x72, 0x61, 0x76, 0x22, 0x21, 0x0a, 0x0b, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x28, 0x0a,
	0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x49, 0x0a, 0x0d, 0x50, 0x61, 0x74, 0x68, 0x54,
	0x72, 0x61, 0x76, 0x65, 0x72, 0x73, 0x61, 0x6c, 0x12, 0x38, 0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x77,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x2e, 0x70, 0x74, 0x72, 0x61, 0x76, 0x2e,
	0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x74,
	0x72, 0x61, 0x76, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x61,
	0x72, 0x6d, 0x2f, 0x70, 0x74, 0x72, 0x61, 0x76, 0x2f, 0x70, 0x74, 0x72, 0x61, 0x76, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ptrav_ptrav_proto_rawDescOnce sync.Once
	file_ptrav_ptrav_proto_rawDescData = file_ptrav_ptrav_proto_rawDesc
)

func file_ptrav_ptrav_proto_rawDescGZIP() []byte {
	file_ptrav_ptrav_proto_rawDescOnce.Do(func() {
		file_ptrav_ptrav_proto_rawDescData = protoimpl.X.CompressGZIP(file_ptrav_ptrav_proto_rawDescData)
	})
	return file_ptrav_ptrav_proto_rawDescData
}

var file_ptrav_ptrav_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ptrav_ptrav_proto_goTypes = []interface{}{
	(*PathRequest)(nil),  // 0: ptrav.PathRequest
	(*ContentReply)(nil), // 1: ptrav.ContentReply
}
var file_ptrav_ptrav_proto_depIdxs = []int32{
	0, // 0: ptrav.PathTraversal.ShowContent:input_type -> ptrav.PathRequest
	1, // 1: ptrav.PathTraversal.ShowContent:output_type -> ptrav.ContentReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ptrav_ptrav_proto_init() }
func file_ptrav_ptrav_proto_init() {
	if File_ptrav_ptrav_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ptrav_ptrav_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ptrav_ptrav_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ptrav_ptrav_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ptrav_ptrav_proto_goTypes,
		DependencyIndexes: file_ptrav_ptrav_proto_depIdxs,
		MessageInfos:      file_ptrav_ptrav_proto_msgTypes,
	}.Build()
	File_ptrav_ptrav_proto = out.File
	file_ptrav_ptrav_proto_rawDesc = nil
	file_ptrav_ptrav_proto_goTypes = nil
	file_ptrav_ptrav_proto_depIdxs = nil
}
